name: inno_commute
description: App to looking for companions to going to Kazan from Innopolis and opposite.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cloud_firestore: ^3.1.10
  crypto: ^3.0.1
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_datetime_picker: ^1.5.1
  select_dialog: ^2.0.0
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
